### ISSUE TITLE
Can't sideload UWP apps on work laptop

### ISSUE THREAD

**Issue by nithjino** [felixse/Woop#2]
I am trying to install this on my work laptop since boop-gtk dropped windows support. I can't change the settings to allow sideloading of UWP apps. Are there plans to have a standard installer?

**Comment by felixse** [comment]
Are you allowed to download it from the Microsoft Store?

I don't think there is any other way to install an UWP app besides sideloading and the Store

**Comment by nithjino** [comment]
> 
> 
> Are you allowed to download it from the Microsoft Store?
> 
> I don't think there is any other way to install an UWP app besides sideloading and the Store

no MS store access either sadly

**Comment by felixse** [comment]
So they let you install an unsigned .msi like Boop-GTK but not a sandboxed app? 🤔

I'm afraid I cannot help you with this, seems more like an issue with your IT department.

**Comment by nithjino** [comment]
> 
> 
> So they let you install an unsigned .msi like Boop-GTK but not a sandboxed app? 🤔
> 
> I'm afraid I cannot help you with this, seems more like an issue with your IT department.

lol yah. pretty strange. only a few people can install software like that (devops and some devs) but they still don't allow UWP sideloading for the same people. Just wanted to ask and see if it was possible.
